### ISSUE TITLE
EPIC: Hackathon

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#328]
Vi tror att ett hackathon kan skapa PR för oss samtidigt som vi få nya ideer och ett större nätverk. Till skillnad från idag då vi är väldigt anonyma och inte har mission 2025 klar än så kan detta hjälpa oss. Vi vet att detta är sant när utvärderingen från deltagarna visar på detta.

AC:
- [ ] Kolla om det går t att anordna svenska mästerskapet 
- [ ] Jury finns
- [ ] Minst 10 deltagade team anmält sig senast 5/10.
- [x] Tydliga regler finns
- [x] Annonser/banners utskickade
- [x] #358 
- [x] #519 
- [ ] Hacakaton genomfört
- [ ] Vinnare utsedd
- [ ] Utvärderingen visar på bra betyg

**Comment by Overath** [comment]
@patryk-banach och  @FannyBacklin kan ni haka på denna så spånar vi vidare?

**Comment by Overath** [comment]
Först ut för att bryta ner denna är ett startmöte. Det team som tar sig an uppgiften bjuder in till detta med berörda.

**Comment by overath2** [comment]
Moving back to Ready waitint for driver.

**Comment by overath2** [comment]
Här förslag på storys för nedbrytning av denna epic.
- Skapa banner till vår hemsida
- Skapa nyhet till vår hemsida
- Bestämma regler
- Ragga jury
- Ragga deltagare

**Comment by overath2** [comment]
@patryk-banach och @jani-at-noq ni hade bra idéer här. Vill ni plocka denna?

**Comment by overath2** [comment]
Kan du kolla denna @FannyBacklin?

**Comment by overath2** [comment]
Stor risk att denna läggs ned på grund av för få anmälningar.

**Comment by FannyBacklin** [comment]
Nej vad tråkigt.. När tar vi det beslutet?

**Comment by overath2** [comment]
Ikväll.

**Comment by overath2** [comment]
Avslutar. För få anmälda.
