### ISSUE TITLE
EPIC: Gäster (was Brukare)

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#395]
Vi tror att en digitalt stöd för hemlösa/brukare/gäster är något som skulle kunna underlätta för dessa att hitta en sovplats för natten. Till skillnad från idag då de står i kö för att eventuellt få en sovplats där de känner sig otrygga.

Vi vet att detta är sant när en brukare/hemlös/gäst sagt att vårt stöd är en del av lösningen.

###Acceptanskriteria

- [x] Gäst kan logga in  
- [x] Gäst kan se lediga sovplatser
- [x] Gäst kan boka ledig sovplats

**Comment by overath2** [comment]
Hej alla assignees. Jag skulle vilja ha en assignee/driver/epic owner på alla epics enligt principen "för många kockar". Kan ni flytta över er till fältet Wingmate istället och kan någon räcka upp handen som epic owner?

**Comment by overath2** [comment]
Se även https://docs.google.com/presentation/d/13eRs4bCL9AtUPST6hW5dj_hvTEtqnuhcl1_in5tfZcs/edit?usp=drivesdk

**Comment by overath2** [comment]
Ping @FannyBacklin . Kan du kika på denna?

**Comment by overath2** [comment]
@LucyMoth @FannyBacklin @callekrook kan bara 1 vara epicowner här?

**Comment by overath2** [comment]
@callekrook kan du vara epic owner för denna?

**Comment by overath2** [comment]
Sätter dig @callekrook som epic owner tills någon räcker upp handen.
Uppdaterad kravspecifikation: https://drive.google.com/file/d/1qi082jRbWu4oZZIaqHL2p6gJBTGxX2Cs/view?usp=drive_link

**Comment by overath2** [comment]
Obs! Gästen och volontärer använder mobilt gränssnitt medan handläggare och admin använder PC. Respektive login måste optimeras för detta.

**Comment by overath2** [comment]
Status @callekrook ?

**Comment by FannyBacklin** [comment]
@callekrook @Overath Alla de här tre funktionerna finns väl nu? Så den här är klar? :)

**Comment by overath2** [comment]
OK, sätter till klar. Demon = demon 10/10.
