### ISSUE TITLE
EPIC: GitHub cleanup

### ISSUE THREAD

**Issue by Overath** [noQ-sweden/noq#445]
Vi tror att ett enklare GitHub gör att vi alla kan arbeta mer optimalt med verktyget. Till skillnad från idag då det finns många projekt etc som gör att man inte förstår vad som finns var. Vi vet att detta är sant när alla i noQ har utbildats i GitHub och gör tumme upp på denna förbättring.

Tasks:

- [X] 1. Minska antalet boards
Used Boards https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#bookmark=id.u2h3xv9ocblc
- [x] 2. Minska antalet projekt // in Progress
Checking if we can close down CMS
- [x] 3. Minska antalet repositories  // in Progress
Checking if we can close down CMS
noq is used as projects space
- [x] 4. Säkerställ att vi jobbar säkert med koden - this should be a a new big ticket
[ ] #458 
- [x] 5. Dokumentera Ways of Working med GitHub
https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#bookmark=id.u2h3xv9ocblc
https://github.com/noQ-sweden#github
- [ ] 6. Skapa utbildning för detta
- [ ] 7. Alla på noQ utbildade
- [ ]  8.  Uppdatera sidan https://github.com/noQ-sweden så att den tydligt svarar på frågan "vilken tech stack använder vi" för en utomstående.

**Comment by overath2** [comment]
Hej @Gafrelek hur går det här.

**Comment by Gafrelek** [comment]
Asked Fanny for some updates but pretty sure we can delete CMS related repo and project. 
GH security is bigger topic i will talk with Erik and create a new EPIC for that, 
Ways of working are done

when rest is clarified i will make post on Slack

**Comment by overath2** [comment]
I am readys as wingmate!

**Comment by Gafrelek** [comment]
Removed unnecessary repos an project.
Need to update documentation and create a ticket

**Comment by overath2** [comment]
Kan du kolla denna @FannyBacklin?

**Comment by Gafrelek** [comment]
Meanwhile new repos got added, need to review them again but should be done in September

**Comment by Gafrelek** [comment]
@Overath 
 6. Skapa utbildning för detta
 7. Alla på noQ utbildade
 I saw you updated documentation in playbook and added video! 
8: 
![Image](https://github.com/user-attachments/assets/888e1c48-93e0-45c8-8656-79b350a8a81e)

Added repos info to Playbook, suggested deleting the old info
overall waiting for clarification about one repo to delete and i think this can be closed

**Comment by overath2** [comment]
Cool! Thanks @Gafrelek . Dont forget to handover to your toolmaster wingmate for Github as well.
