### ISSUE TITLE
EPIC: Ny roll - Volontär

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#509]
Vi tror att en tjänst för att volontärer som skall kunna agera stödpersoner för gäster som inte har mobiltelefon att boka själva, ger dessa möjlighet att boka sovplats i vår app, men även fler volotäruppdrag på boställen.
Till skillnad från idag då gäster inte kan boka via vår app samt volontäruppdrag är svåra att administrera.
Vi vet att detta är sant när volontärer och gäster upplever en klar förbättring senast 2025-02-01.

AC:

- [x] Fritextfält UNO-kod för bokning via volontär #673 
- [x] Volontär kan boka sovplats åt gäst [#644](https://github.com/noQ-sweden/noq/issues/644)
- [ ] Volontär har en startsida/dashboard där de lätt ser lediga uppdrag samt egna åtaganden. Dashboard för Volontärer [#643](https://github.com/noQ-sweden/noq/issues/643)
- [ ] Volontär kan boka lediga volontäruppdrag på alla boenden [#646](https://github.com/noQ-sweden/noq/issues/646)
- [ ] #759

**Comment by overath2** [comment]
Jag har bokat fyra dagar i december då jag (och gärna fler) skall gå på stan och ragga gäster av hemlösa i Stockholm.
Då vill jag använda vår app inloggad som volontär.

**Comment by overath2** [comment]
Tja @callekrook ! Status här?

**Comment by overath2** [comment]
Grymt. Underliggade stories har status backlog och ligger i sprint 10. Antingen sprint 11 eller status ready?

**Comment by overath2** [comment]
Vill gärna ha någon assignee här. Om inte måste POs ta denna.

**Comment by overath2** [comment]
Kan du ta denna @natischmidt ?

**Comment by overath2** [comment]
Kan någon annan ta denna? @LudvigErlandsson eller @patrik-pwned kanske?

**Comment by LudvigErlandsson** [comment]
@jani-at-noq Kan du vara wingmate här? För att säkerställa att vi tar hela volontär-epic i mål inför Demo och MVP

**Comment by jani-at-noq** [comment]
Ok

**Comment by overath2** [comment]
Skulle vilja att denna har leverans release 25-2.

**Comment by overath2** [comment]
Ping @LudvigErlandsson

**Comment by overath2** [comment]
Går igenom epics. Kan denna få en uppdatering? Ping @LudvigErlandsson !
