### ISSUE TITLE
EPIC: Data science och AI

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#514]
Vi tror att datat vi kommer att hantera måst skötas på ett professionellt sätt med maximum integritet och moral samtidigt som vi provar  på att integrera AI i vår befintliga produkt så att handläggare kan få intelligenta rapporter.
Till skillnad från idag då handläggare jobbar med filimport till Platina och måste gör manuella rapporter för att få insikter så kan vå produkt säkerställa enkelhet, hög datakvalitet och stor integritet.
Vi vet att detta är sant när en handläggare gett oss tumme upp på vår MVP.

- [x] Sätta upp datateam #581 
- [x] Sätta upp backlog för 2024
- [x] Skapat strategi för GDPR #593 
- [x] Förslag på AI stöd skapat för 2025
- [ ] En rapport framtagen för handläggare #648

**Comment by overath2** [comment]
Uppstartsmöte 13 september. Välkomna!

**Comment by overath2** [comment]
@elajth kan du vara epic owner för denna?

**Comment by overath2** [comment]
Status @elajth ?

**Comment by elajth** [comment]
Möte med datateamet 25/9, uppdaterar efter det

**Comment by overath2** [comment]
Status @elajth Jag har skapat en story för detta i sprint 9: #581

**Comment by overath2** [comment]
Status @elajth ?

**Comment by overath2** [comment]
Status @elajth och @filipamo ?

**Comment by overath2** [comment]
@filipamo kan du ta över denna?

**Comment by overath2** [comment]
@filipamo kan du stänga denna och föra över det som är kvar till en ny story så får vi städa? Ping @patrik-pwned
