### ISSUE TITLE
Task: Städa och struktuera Figma filen

### ISSUE THREAD

**Issue by ChristofferEriksson-NoQ** [noQ-sweden/noq#515]
###Beskrivning
Som noQare behöver jag tydligare struktur i noQ Figma filen för snabbt lista ut veta vad som är redo att implementeras, vad som arbetas på, och vad som är utdaterat.

###Acceptance Criteria
Förutsatt att jag är i noQ Figma filen ser jag:
Vad som är vad
Vad som är work in progress och vad som är aktuellt
Vad som är redo att implementeras av utvecklare
Design regler och komponenter för UI

###Subtasks
I en kopia av noQ filen:
- [ ] Skapa tydlig struktur i Figma filen
- [ ] Sortera aktuella och utdaterade element
- [ ] Skriv korta beskrivningar till samlingar av element
- [ ] Få godkännande från senior UXare hos noQ innan detta implementeras i primära den Figma filen.

###Definition of Done
OK from wingmate
All subtasks done or cancelled
Max 5 min demo video

**Comment by ChristofferEriksson-NoQ** [comment]
Glömde att lägga till en länk till struktur förslaget, så nu finns den här nedan!
[https://www.figma.com/design/AYLDDKvzNmPZnocPGfdyT4/noQ---Reformat-proposal?node-id=0-1&t=WChMtguXBk4HDbxv-1](https://www.figma.com/design/AYLDDKvzNmPZnocPGfdyT4/noQ---Reformat-proposal?node-id=0-1&t=WChMtguXBk4HDbxv-1)

**Comment by ChristofferEriksson-NoQ** [comment]
Lämnar en länk till en säkerhets kopia av originalet här: https://www.figma.com/design/ifbf42giDiucaQOuR8HGlQ/noQ-(Copy)?m=auto&t=EGpwlA9ZVGaBDhea-1

**Comment by ChristofferEriksson-NoQ** [comment]
Redo för review av wingmate
