### ISSUE TITLE
EPIC: Preferences

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#525]
As a user (any) i need to be able to create/update my data so the system shows correct information about me so i can have a interface that fits me.

AC:

- [x] All personal data: UNO, Firstname, Lastname, email, mobile phone
- [x] UNO code not possible to change after registration
- [x] Delete me
- [x] Toggle language between Swedish and english (later romaninan an polish)
- [x] Add/Change my photo/avatar
- [x] Change password
- [x] My presentation
- [x] Possible to add one person supporting for help.

**Comment by patrik-pwned** [comment]
Vill vi ha med möjligheten att ange en kontaktperson? typ en nöd- eller familjekontakt

**Comment by overath2** [comment]
Here is some input. Ping @patrik-pwned for feedback: https://docs.google.com/spreadsheets/d/19fOZppnyLdcYe8LhArVcfd5FeCwtB10rMtTY4cbaI-o/edit?usp=sharing

**Comment by patrik-pwned** [comment]
Is there a good reason why birthyear, birthday and gender is mandatory for admin and caseworker?

And the birthday for the volunteer?

**Comment by overath2** [comment]
UNO = FLYYDD (Ove Holmberg = OH6325)
Perhaps only valid for guests? Or for all users?

**Comment by patrik-pwned** [comment]
I can get understand for volunteers but not so much for admin or caseworkers because we control their access anyway and they're not so many 😉

**Comment by overath2** [comment]
OK, then modify the sheet accordingly.

**Comment by NicoleZafra1** [comment]
Hi Preferences is finished here is the Figma design:  https://www.figma.com/design/EaJazrXmoTOQ6kNj1JoLTU/Preferens?node-id=0-1&t=CrZOPHqIuR8V8uqT-1 What do u guys think?

**Comment by overath2** [comment]
No hurry with this but please comment status here more often @NicoleZafra1 @Ovura-noq @amandawinberg

**Comment by overath2** [comment]
No hurry with this but please comment status here more often @NicoleZafra1 @Ovura-noq @amandawinberg

**Comment by overath2** [comment]
Status @NicoleZafra1 @Ovura-noq @amandawinberg?

**Comment by amandawinberg** [comment]
@NicoleZafra1 @overath2 I thought Nicole had moved it to done but it's done! This has been moved to the main NoQ figma life and ready for development.

**Comment by overath2** [comment]
Repoen and move to new project.

**Comment by overath2** [comment]
What is status here @NicoleZafra1 @amandawinberg @Pooja-prad @Priyanka-katal @kavitha123-art ?

**Comment by NicoleZafra1** [comment]
Figma sketches is done

**Comment by overath2** [comment]
Assigning @NicoleZafra1 only as we need only one (1) epic owner/assignee per epic.

**Comment by overath2** [comment]
This is overdue. Closing.
