### ISSUE TITLE
EPIC: Trygg i min roll

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#537]
Som en noQare vill jag vara trygg i min roll så jag kan dels leva upp till förväntningar från noQ men även ha lite att lära mig så jag och noQ kan växa.

AC:

- [ ] Alla i noQ förstår innebörden av att vara trygg i sin roll.
- [ ] Alla i noQ har skrivit sin egen rollbeskrivning
- [ ] Alla i noQ har skrivit sin skillsmap.
- [ ] Alla i noQ säger att de är trygga i sin roll.

**Comment by overath2** [comment]
Ska vi ta ett första möte i oktober?

**Comment by overath2** [comment]
Vill ha med HR även i denna som wingmate eller driver.

**Comment by overath2** [comment]
Avvaktar möte med Jessica

**Comment by overath2** [comment]
Notera att TIMR ingår om en subprocess till #421

**Comment by overath2** [comment]
Kan du @FannyBacklin fixa Jessica som wingmate? Ingen brådska.

**Comment by overath2** [comment]
Går igenom epics. Kan denna få en uppdatering? Vem är driver/asignee/wing? Ping @FannyBacklin

**Comment by FannyBacklin** [comment]
@overath2 kikar och återkommer!
