### ISSUE TITLE
EPIC: Finansiering

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#538]
Vi tror att ordning på finanser är viktigt för en ideell organisation som oss, till skillnad från idag då vi inte har något bankkonto och endast en kassör med inget att göra i styrelsen.
Vi vet att detta är sant när vi upplever att vi har ordning på våra finanser.

AC:

- [ ] Kassör trygg i sin roll
- [x] Bankkonto skapat
- [x] Swishkonto skapat
- [ ] Budget för 2025 skapad inklusive källor för intäkter (medlemskap, bidrag, spons, kampanjer, patreon etc)
- [x] Kickstarter #628 
- [ ] #384 
- [ ] Kontakta Folkuniversitetet om studiecirklar
- [ ] https://www.milliegiving.com/

**Comment by overath2** [comment]
Kassör spikas på extra årsmöte. @Mrsluggan jobbar med att ragga detta.

**Comment by overath2** [comment]
https://foreningsservice.stockholm/stod-till-foreningar-och-kulturaktorer/socialstod/foreningsstod-fran-socialforvaltningen/

**Comment by jani-at-noq** [comment]
AWS har krediter för ~10% av kostnaden för non-profits. Ska vi lägga till här?
https://www.techsoup.se/content/amazon-web-services-credit-smaller-nonprofits

**Comment by patrik-pwned** [comment]
Hittade detta också: https://support.google.com/a/answer/9752995?sjid=5231042302822243002-EU

**Comment by overath2** [comment]
> Hittade detta också: https://support.google.com/a/answer/9752995?sjid=5231042302822243002-EU

Bra. Vi spar den till vi har ekonomin

**Comment by overath2** [comment]
Har flyttat in länkarna här: https://docs.google.com/spreadsheets/d/1_7z5gIxXBDcWXEh3iXki1q-w0S1r25MF-z3t6ApotPA/edit?usp=sharing

**Comment by overath2** [comment]
https://ready.csod.com/GlobalSearch/search.aspx?s=1&q=%23Fundraising_resources_NPR

**Comment by overath2** [comment]
https://www.disasterready.org/
