### ISSUE TITLE
EPIC: GDPR

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#550]
**Hypothesis**
We believe that GDPR compliance will help noQ achieve more customers
Unlike today when noQ have no compliance,
Our solution will make sure noQ gets GDPR compliance.
We know this is true when the following metrics has been ticked off:

**Metrics**
- [ ]  100% GDPR compliance latest 20241201
- [ ]  Thumbs up from 1 customer latest 20241201

**Acceptance Criteria**
* Given we have all metrics measured
* When we look attt the output
* Then we can decide if this hypothesis was true or false

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
Notera att uno-kod är ok enligt GDPR . Ping @filipamo @elajth

**Comment by overath2** [comment]
Hur går det här @filipamo och @elajth ?

**Comment by filipamo** [comment]
1. Vi måste skriva ett dokument. Det är möjligt att göra det med en onlinetjänst som kräver betalning.
2. Vi kan inte skriva dokumentet medan vi inte har bestämt oss för vilken data vi kommer att samla in och hur vi ska samla in dessa uppgifter

@overath2

**Comment by overath2** [comment]
Vilken data bör framgå av datamodellen vi jobbar med? Hur vi ska samla in är dock oklart. Via appen - räcker inte det?

**Comment by elajth** [comment]
Hej @overath2  @filipamo! Mer info (checklista) på vad vi behöver göra innan vi kan vara GDPR compliant finns i #593  och i 
https://docs.google.com/document/d/1i12Z_wpvWHbl0i8R4QkE18z5DlMVm6O79AHeS6b-zEI/edit?tab=t.0
Kort och gott:
Första steg enligt mig är att ta hjälp av jurist med att starta upp dokumentationen. Sen klarar vi säkert det mesta själva men vi behöver riktlinjer. Det finns inga konkreta riktlinjer på integritetsmyndigheten. Det finns många aktörer som påstår att de kan hjälpa till men ingen gratis vad vi kan hitta.

**Comment by overath2** [comment]
Gott. Kan ni ta en slide på detta på demon?

**Comment by overath2** [comment]
@filipamo kan du ta denna?
