### ISSUE TITLE
EPIC: noQ academy 

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#551]
**Hypothesis**
We believe that a noQ academy will help noQ people achieve more
Unlike today when noQ people have   no internal training. 
Our solution will make sure noQ people become comfortable in their roles.
We know this is true when the following metrics has been ticked off:

**Metrics**
- [ ] All productowners and teamleads gives thumbs up latest 201210 for scaling this to others.

**Notes from the board**
Jag skulle vilja sätta upp ett noQ-academy som en interntjänst för utbildning och att bli trygg i sin roll. Initialt skulle jag vilja ha en "learning path" för team lead och scrum masters som jag kan hålla. En path leder alltid till att bli trygg i sin roll och har 3-5 småkurser på max 1 timma med hemläxa emellan. Förslag på upplägg för en SM.
 Agile, Scrum, Lean, Holocracy
 Facilitering och coaching
 Ceremonier
 Tickets i GitHub
Förslag: Att alla SM/teamlead skall ha gått denna senast 10/12 för utvärdering och ev kopiering till andra roller.

**Acceptance Criteria**
* Given we have all metrics measured
* When we look attt the output
* Then we can decide if this hypothesis was true or false

- [x]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [x]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
Content: https://drive.google.com/drive/folders/1xh--tFoAw6ziGTJnf3v9QEd9_JYxUw3U?usp=drive_link

**Comment by overath2** [comment]
Page created but hidden: https://noq.nu/2041-2/

**Comment by FannyBacklin** [comment]
@overath2 vem är wingmate på denna?

**Comment by overath2** [comment]
Bra fråga. Jag tänkte just fråga ;). Jag skapar materialet några dagar innan typ ikväll. Jag har satt tema team nu på onsdag där du hade lite inspel så kanske du @FannyBacklin kan vara det?

**Comment by FannyBacklin** [comment]
Absolut!

**Comment by overath2** [comment]
Har pingat dig i decken.

**Comment by overath2** [comment]
2 av 5 tillfällen klara

**Comment by overath2** [comment]
3 av 5 tillfällen klara

**Comment by overath2** [comment]
Vi pausar denna och återkommer 2025
