### ISSUE TITLE
EPIC: Ideburet Offentligt Partnerskap (IOP)

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#603]
**Hypothesis**
We believe that Ideburet Offentligt Partnerskap (IOP) will help noQ people to get paid for the work so noQ can set up expectations on delivery and partnertship with other organisations will be helpful.
Unlike today when we have no partners and no financials.
Our solution will make sure we gets a delivey focused organisation with great progress and great partners.
We know this is true when the following metrics has been ticked off:

**Metrics**
- [ ]  Minumum 2 partners working with us in a IOP
- [ ]  Ability to pay delivery focused noQ workers.

**Acceptance Criteria**
* Given we have all metrics measured
* When we look attt the output
* Then we can decide if this hypothesis was true or false

**Sub issues/tickets:** 
* One
* Two
* Three

**Other info:** 
[Ex: Links, Solutions, best practices etc.](https://socialforum.se/vara-verksamheter/verksamheter-och-projekt/ideburet-offentligt-partnerskap/)

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by patrik-pwned** [comment]
[stockholms-stads-riktlinjer-for-iop.pdf](https://github.com/user-attachments/files/17392753/stockholms-stads-riktlinjer-for-iop.pdf)

**Comment by patrik-pwned** [comment]
https://foreningsservice.stockholm/foreningar/

**Comment by overath2** [comment]
Snyggt! Har läst och ser inga problem att ansöka. Kanske till våren?

**Comment by patrik-pwned** [comment]
Har ett minne av att nästa ansökningsperiod stänger i början av januari. Försöker hitta var jag läste detta men det är vårt fönster

**Comment by overath2** [comment]
Har skapat folder för IOP. Vi sätter igång i Januari.
https://drive.google.com/drive/folders/102qWmPBh-O6kce0nBeBmHAXs1_fUTFZo?usp=drive_link

**Comment by overath2** [comment]
Done!

**Comment by overath2** [comment]
I have had several conversations on email with the Stockholm town. Please see folder: https://drive.google.com/drive/folders/102qWmPBh-O6kce0nBeBmHAXs1_fUTFZo?usp=drive_link

Plan for meeting in april.

**Comment by overath2** [comment]
Negative. But we will continue Autumn 2025.
