### ISSUE TITLE
EPIC: Partner- and memberships

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#604]
**Hypothesis**
We believe that Partner- and memberships will help us  achieve better outcome for homeless.
Unlike today when we operate alone and have no or few members-or partnerships
Our solution will make sure we gets forums for collaboration
We know this is true when the following metrics has been ticked off:

**Metrics**
- [ ]  We have 1 membership in a network latest 2024-12-10
- [ ] We have 2 partnerships latest 2024-12-10

**Acceptance Criteria**
* Given we have all metrics measured
* When we look attt the output
* Then we can decide if this hypothesis was true or false

**Sub issues/tickets:** 
* One
* Two
* Three

**Other info:** 
[Ex: Links, Solutions, best practices etc.
](https://socialforum.se/vara-medlemmar-2/)

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
Partnership should include membership in reference group if they want.

**Comment by overath2** [comment]
Söker wingmate...

**Comment by overath2** [comment]
Skulle vilja testa med Chief, KnowIT och Questit. Ping @FannyBacklin
