### ISSUE TITLE
EPIC: DORA compliance

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#605]
**Hypothesis**
We believe that DORA compliance will help us achieve secure data reporting with our clients
Unlike today when we have no DORA compliance
Our solution will make sure  we get a secure data reporting platform.
We know this is true when the following metrics has been ticked off:

**Metrics**
- [ ]  DORA compliant latest 2025-04-01

**Acceptance Criteria**
* Given we have all metrics measured
* When we look attt the output
* Then we can decide if this hypothesis was true or false

**Sub issues/tickets:** 
* One
* Two
* Three

**Other info:** 
[Ex: Links, Solutions, best practices etc.](https://www.pwc.se/dora)

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
Se mall jag har lagt i tellus-mappen i drive

**Comment by overath2** [comment]
Spike i januari? Ping @elajth @filipamo

**Comment by overath2** [comment]
Ping @elajth @filipamo

**Comment by overath2** [comment]
@filipamo kan du ta denna?

**Comment by filipamo** [comment]
From what I have read this related only to the financial sector. Or how do you see it fit into noQ? @overath2

**Comment by overath2** [comment]
Yes it is. My bad. Lets close.
