### ISSUE TITLE
EPIC: Gapminder partnership

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#606]
**Hypothesis**
We believe that a gapminder partnership will help us achieve better reports
Unlike today when we have the Socialstyrelsen survey from 2023 only
Our solution will make sure our clients gets correct statistics.
We know this is true when the following metrics has been ticked off:

**Metrics**
- [ ]  Partnership (or similar) with Gapminder latser 2025-03-01

**Acceptance Criteria**
* Given we have all metrics measured
* When we look attt the output
* Then we can decide if this hypothesis was true or false

**Sub issues/tickets:** 
* One
* Two
* Three

**Other info:** 
Ex: Links, Solutions, best practices etc.

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
@elajth kan du börja refina denna med @filipamo ?

**Comment by overath2** [comment]
Status @elajth och @filipamo ?

**Comment by overath2** [comment]
Status @elajth och @filipamo ?

**Comment by overath2** [comment]
Status @elajth @filipamo @SelsabeelA ? Assigning @filipamo

**Comment by overath2** [comment]
Good. Keep calling them.

**Comment by overath2** [comment]
Cleaning up. Can we close this ticket? Ping @filipamo
