### ISSUE TITLE
EPIC: Training Google toolmasters with automated new user process

### ISSUE THREAD

**Issue by inhyenoq** [noQ-sweden/noq#608]
**Hypothesis**
We believe that Training Google toolmasters with automated new user process will help us achieve to maintain this automated process stably.
Unlike today when only I am ready for changing or improvement of the apps script
Our solution will make sure a gets all Google tool masters can work on it.
We know this is true when the following metrics has been ticked off:

**Metrics**
- [ ] All Google toolmasters who are active at the present time have completed the training. 

**Acceptance Criteria**
* Given we have all metrics measured
* When we look attt the output
* Then we can decide if this hypothesis was true or false

**Sub issues/tickets:** 
- [x] Updating the script with #635 #674 
- [ ] Build a training method for Google toolmasters

**Other info:** 
- Related ticket #411 
- [Process documentation](https://docs.google.com/spreadsheets/d/1O48R1ewvlh2vvHfsv018soZM1q1kAPgMgtlMpCz0GlA/edit?gid=216586837#gid=216586837&range=A1)

**Comment by overath2** [comment]
Done november? Ping @inhyenoq

**Comment by inhyenoq** [comment]
@overath2 I will try!

**Comment by inhyenoq** [comment]
@overath2 Could you clarify the priority between #635 and this one?

**Comment by overath2** [comment]
I belive they can be merged. This is training while #635 is more automation of the process.

**Comment by inhyenoq** [comment]
@overath2 Could you take the wingmate for this?

**Comment by overath2** [comment]
Sure!

**Comment by overath2** [comment]
Kan du flytta denna till 2025 @inhyenoq ?

**Comment by overath2** [comment]
Status @inhyenoq ?

**Comment by inhyenoq** [comment]
Det är redo att börja men är kanska låg prioritet.

**Comment by overath2** [comment]
Cleaning up. Can we close this ticket? Ping @inhyenoq

**Comment by inhyenoq** [comment]
The new Google Toolmaster, Gregor, successfully took over the Apps script project with the help of documentation on [the script itself](https://script.google.com/d/1wSgaCbqBU3Oa0K6r0QIxNYEGcSCcvvBoCvqumBRRh34Rn-TZluBWcO1S/edit?usp=drive_link) and [Google Drive](https://drive.google.com/drive/folders/15cNE0XvrXg_D5fDztruqTlcwSEveKNaD?usp=drive_link) and will maintain and improve the project. I believe, in this way, new toolmasters also can learn how to work on the project.
