### ISSUE TITLE
Merch 2.0

### ISSUE THREAD

**Issue by ChristofferEriksson-NoQ** [noQ-sweden/noq#619]
**Story**
Nu när vi har prototyper av T-shirts kan vi test köra det på liten skala (max 10 tröjor), för att förbättra processen och göra det smidigare att skapa framtida merch.

**Acceptance Criteria**
Förutsatt att test produktionen har utförts
Ska insikter ha sammanställts
Så ska vi ha en smidig process för att hantera merch och se till att andra kan ta över processen om det skulle behövas i framtiden

**Subtasks (checklist)**
- [ ]  Kör test produktion i liten skala
- [ ]  Se över nuvarande system för att lägga in och hantera beställningar och se om det kan förbättras
- [ ] Utforskat möjligheter för stickers
- [ ] Ladda upp relevanta filer för bl.a. trycken på tröjor på drive
- [ ] Skrivit kort rapport

- [ ]  **Definition of Done OK?**
OK from wingmate
Code checked in
All subtasks done or cancelled
Max 5 min demo video

**Comment by overath2** [comment]
Denna blev ej ready i sprintplaneringen så jag flyttar till sprint 11
