### ISSUE TITLE
EPIC: Prevent spoofing, phishing, and spam

### ISSUE THREAD

**Issue by inhyenoq** [noQ-sweden/noq#625]
**Hypothesis**
As Google Workplace admins, we believe that preventing spoofing, phishing, and spam will help us solve email delivery issues.
Today, new members find noQ account invitation emails in their spam box sometimes.
Complying Gmail security precautions will help our emails to arrive in inbox.

**Acceptance Criteria**
* Check if we have done all Gmail security precautions and complete any found.
- [x] #655
- [x] [Set up SPF](https://support.google.com/a/answer/33786?hl=en&ref_topic=9061731)
- [x] #656
- [x] #664
- [x] #657

**DoD**
OK from wingmate
Documented
When we check domain MX up, we can see
- [x] DKIM has been set up
- [x] SPF has been set up
- [x] DMARC has been set up
- ~~BIMI has been set up~~
- [x] no significant errors or warnings are found on the MX diagnosis results.
- [ ] The gradual rollout of DMARC has been completed to at least the "quarantine" level.

**Comment by inhyenoq** [comment]
### Domain MX diagnosis results
https://toolbox.googleapps.com/apps/checkmx/check?domain=noq.nu&dkim_selector=

##### error
* Domain must have at least one mail server.
##### warning
* DKIM is not set up.
* DMARC is not set up.
* MTA-STS DNS Record.
* No Google mail exchangers found. Relayhost configuration?
##### info_outline
* Effective SPF Address Ranges.
##### done 
* Domain should have at least 2 NS servers.
* Naked domain must be an A record (not CNAME). done
* Every name server must reply with exactly the same TXT DKIM records. 
* Every name server must reply with exactly the same TXT DMARC records.
* Every name server must reply with exactly the same TXT MTA-STS record.
* Every name server must reply with exactly the same CNAME records.
* Every name server must reply with exactly the same NS records.
* Every name server must reply with exactly the same MX records.
* Every name server must reply with exactly the same TXT records.
* SPF must allow Google servers to send mail on behalf of your domain.

**Comment by inhyenoq** [comment]
DMARC under monitoring.
Find reports here: https://docs.google.com/spreadsheets/d/1X5fF27xErjEwx3B89S6DZwEjRc-R2obRGvZHjB_V1Rw/edit?usp=sharing (Access available Google toolmasters only)

**Comment by overath2** [comment]
Can we postpone until 2025? No need for MVP?

**Comment by inhyenoq** [comment]
@overath2 Oh, the last step of this Epic is mainly monitoring, and it takes about 10 minutes per week.. Just it will take a quarter.

**Comment by overath2** [comment]
Cool. Lets do it in 11.

**Comment by overath2** [comment]
Or 12. Ping @inhyenoq

**Comment by inhyenoq** [comment]
There is a ticket for that already.... https://github.com/noQ-sweden/noq/issues/657

**Comment by overath2** [comment]
OK, lets put this in review?

**Comment by inhyenoq** [comment]
@overath2  Thanks for the reminder. This one has a dependency on #657, which requires a long period (not working time but a long time span) to complete. I will put it in review when it is ready. I put this and #657 in backlog since you don't need to check it until that time.

**Comment by inhyenoq** [comment]
It seems that all the above setups have lost while moving the domain hosting service from Loopis to AWS.
Therefore, the process should be done again from the beginning. I close this Epic and reissue new.
