### ISSUE TITLE
EPIC: Automated onboarding checklist

### ISSUE THREAD

**Issue by inhyenoq** [noQ-sweden/noq#635]
**Story**
As a newcomer I need a clear and easy-to-use onboarding checklist so I can trace and complete my onboarding process successfully.

**Acceptance Criteria (checklist)**
- [x]  Offer a workplace where HR can update the template, using ordinary documenting tools. e.g. Google sheets
- [x]  Automate the process that creating a personal checklist for each newcomer, integrating the new Google user creation process.
- [x]  Create a easy-to-use interface for newcomers, so they can easily navigate onboarding materials and follow own progress.
- [x]  Provide HR with an overview of onboarding progress that each newcomer is marking.

**Acceptance Criteria (BDD)**
* Given the checklist template has been set by HR
* When the system invites a new Google user with the automatic process
* Then a personal onboarding checklist will be created automatically, and the new user will receive its link.

**Other info:** 
- Checklist:
https://docs.google.com/spreadsheets/d/18yIHDLdlSH5xFzHXF5dZg3x020kdp3Z0Bf_99HGJnDY/edit?usp=sharing
- Automatic onboarding process #607 

**Definition of Ready OK?**
- [X] Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

**Definition of Done OK?**
- [x] All AC checklist marked
- [x] AC BDD marked
- [x] A guidance for People & Culture: https://docs.google.com/presentation/d/1uTsHuw01LSz4dpkOlknFarIMsXTtyD0OGacQs7HeM8A
- [x] Updated process flow: https://drive.google.com/file/d/1AYPi8w6raKYrBHf2UDKyyz71lAxEQ4W6
- [x] Updated playbook
- [x] At least one successful case with a newcomer

**Comment by overath2** [comment]
@inhyenoq can you record a 5 minute film about how to write stories so we can use it at the upcoming academy?
Else i will do it with this as an example. Great work!

**Comment by inhyenoq** [comment]
@overath2 Honestly, I just wrote it following the template! Once you make it, I will be able to learn what has been done well from it.

**Comment by inhyenoq** [comment]
Onboarding checklist management
[https://docs.google.com/spreadsheets/d/1qPfNEll81OI5Mhf14_p3CrwgD9KMeUP8_0OizCaTN3M/edit?usp=sharing
Onboarding progress report for PC
](https://docs.google.com/spreadsheets/d/1qPfNEll81OI5Mhf14_p3CrwgD9KMeUP8_0OizCaTN3M/edit?gid=251772020#gid=251772020)

**Comment by overath2** [comment]
Drag to review and ping when reday for test

**Comment by overath2** [comment]
This is awesome! Can you update the flow-diagram with this process? Lets try next week with those who hopefully joins after infomeeting today.

**Comment by inhyenoq** [comment]
Good idea. There are some backend work left to automate copying, connecting etc. But I can manually assign the checklists to those who arrives in the next week.

**Comment by overath2** [comment]
5 ppl new coming in...
Note that ppl with only "stödperson på stan" not shall do the onboarding.

**Comment by overath2** [comment]
Vågar inte ändra men skulle vilja ha in en rad till i checklistan. Är det bara att infoga en rad efter raden om playbooken?
Annars:

In the Playbook read the part about expectations carefully. Link: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit?tab=t.0#heading=h.b9n96jd7qgos

**Comment by inhyenoq** [comment]
@overath2 
Please edit on the "**Items**" sheet following this video. https://github.com/user-attachments/assets/63226a80-f090-4a82-ad5c-62253b617b06
I will make an editor's guide later. But for now, just do it and leave comment on the cell you edited. I will fix it anything crushed (I have saved a backup now. )

**Comment by overath2** [comment]
No hurry. Add process to film and we will do int later. Importand that P&C also can di this.

**Comment by inhyenoq** [comment]
@overath2 kan du testa? Om du lämna ny person på https://forms.gle/ska7T5wiABsZoNz28 systemet gör alla som vanligt, plus skapa checklisten och skicka mail till ny noQ-konto på startdatum.

**Comment by overath2** [comment]
Testade igår och hade hoppats på mail till min privata mail idag då jag satte 30/11 som startdag. Menhittar inget mail?

**Comment by inhyenoq** [comment]
Well, I can see all did work as intended on system logs. The invitation email has been sent on 30/11 for Olle and another for Peter on 2/12 to Ove.holmberg@gmail.com. Onboarding checklist and etc as well. Note that we send only "Skapa ditt nya noq-konto" email to the private email address, and all others go to the new noq email. Could you check your spam box and come back to me?

**Comment by overath2** [comment]
Sorry. It was in the junk folder. We need to inform applicants to check this folder.

**Comment by inhyenoq** [comment]
Yes. That will be helpful.

**Comment by overath2** [comment]
Logged in = OK.
These are the email in inbox:
![image](https://github.com/user-attachments/assets/b96ba157-6a15-451a-9899-ba011e6d1cd0)

**Comment by inhyenoq** [comment]
> 5 ppl new coming in... Note that ppl with only "stödperson på stan" not shall do the onboarding.
What are these people? Are they noQ members? If not, it is ideal to not use our automated process when creating their accounts.

**Comment by overath2** [comment]
Nope. To strt with they will be "hangarounds" just for this one occasion. But perhaps they want to become noqers later.

**Comment by inhyenoq** [comment]
> Nope. To strt with they will be "hangarounds" just for this one occasion. But perhaps they want to become noqers later.

Then, just send the list of their names and private emails to google.toolmaster@noq.nu 
Don't submit through the form.

**Comment by inhyenoq** [comment]
- A guidance for People & Culture: https://docs.google.com/presentation/d/1uTsHuw01LSz4dpkOlknFarIMsXTtyD0OGacQs7HeM8A
- Updated process flow: https://drive.google.com/file/d/1AYPi8w6raKYrBHf2UDKyyz71lAxEQ4W6
- The updated part on the playbook. https://docs.google.com/document/d/1nbKJWM_FspoZzlSmbCFTnHwqOSiT1lfsvzozmtopduY/edit?tab=t.0#heading=h.rzxfhiwmo0ar

**Comment by overath2** [comment]
Excellent work! I will put this to dobe now,. @jespon508 please save the links as your bookmarks.
