### ISSUE TITLE
EPIC: Christmas cleanup

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#699]
We believe that a fresh re-boot is needed so when we come back rested after christmas, we come to a fresh environment where we can work effectively with noq. Unlike today when a lot is redundant and outdated. We know this is true when the christmas leave is over and we find all our metrics is validating the hypothesis.

**Metrics**
- [ ]  Thumbs up from all teams

**Acceptance Criteria (checklist)**
- [x] All stories done or cancelled

**Stories** 
- [ ]  Cleanup meeting done
- [ ] #700
- [ ] #701
- [ ] #702
- [ ] #703
- [ ] #704
- [ ]  #668 
- [ ]  #677 

- [ ]  **Definition of Ready OK?**
Also called DoR, our generic process for checking if this is ready for start. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.3rdcrjn

- [ ]  **Definition of Done OK?**
Also called DoD, our generic process for checking this is done in the right way. See our Playbook here for details: https://docs.google.com/document/d/1ou6wr1sI9IJZaGGSMn_SJvFru5FJQKMDRZY16kBmx5Y/edit#heading=h.23ckvvd

**Comment by overath2** [comment]
Can you grab this @patrik-pwned ?

**Comment by patrik-pwned** [comment]
Sure men behöver lite mer info att gå på i respektive ticket :D

**Comment by overath2** [comment]
Tag hjälp av respektive Toolsmaster. Men i stora drag:

1. Rensa ut gamla användare, kanaler etc
2. Uppdatera Playbook
3. Erbjud utbildning på verktyget

**Comment by overath2** [comment]
Ping @patrik-pwned

**Comment by patrik-pwned** [comment]
Allt är done eller 'canceled' då svar på vissa frågor uteblivits

**Comment by overath2** [comment]
OK, sätter till klar.
