### ISSUE TITLE
Oves checklist för release 14/12

### ISSUE THREAD

**Issue by overath2** [noQ-sweden/noq#724]
Denna task är en komihåglista för mig att senast 10/12 bocka av allt - annars ställer vi in de fyra tillfällena då vi ska gå på stan.

- [ ] Minst 10 sovplatser finns att boka dessa datum 14,15,21,22 december.
- [ ] Schema för stödpersoners arbete skapat och godkänt av minst 4 stödpersoner (@overath2 )
- [ ] Personal på boställe utbildade (@overath2)
- [ ] Buggar funna rättade
- [ ] Användarkonton skapade för stödpersoner och admin eller om det går att skapa själv.
- [ ] Möjlighet att skapa konto för hemlös själv
- [ ] Möjlighet för stödperson att skapa konto åt hemlös
- [ ] Produktionsmiljö uppe med ovanstående funktionalitet

**Comment by overath2** [comment]
Tog er som gisslan @natischmidt @jani-at-noq @FannyBacklin @patrik-pwned 
Kan ni verifiera att dessa är på G och klara till 10/12 då jag ska hålla utbildning för stödpersoner.
Jag anar att det finns ticket för alla annars så skapas de lätt mha de tre prickarna ...  till höger om respektive rad.
Om de finns - ange länken bara.
Heja!

**Comment by FannyBacklin** [comment]
Gällande marknadsföring tänker jag att vi sprider ut afficherna på stan, samt att jag fixar inlägg på linkedin. Är det något mer utöver det du tänker på som jag missat? @overath2

**Comment by overath2** [comment]
Nej det räcker för denna gång @FannyBacklin

**Comment by overath2** [comment]
Pingar in @DCaranqui för godkännande av buggar enligt ovan.

**Comment by overath2** [comment]
Status @DCaranqui ?
